### ISSUE TITLE
make readable:read() bytes argument optional

### ISSUE THREAD

**Issue by checkraisefold** [Bilal2453/luvit-sumneko-meta#6]
https://github.com/Bilal2453/luvit-meta/blob/main/library/stream.lua#L246
Even in Luvit's tests, no bytes argument is passed. It also behaves strangely when trying to read stdin if you try and pass a bytes argument, and as such the only use I can see of it with stdin is with no bytes argument.

**Comment by Bilal2453** [comment]
Thanks for reporting, will look into it soon.

**Comment by Bilal2453** [comment]
That is indeed correct, the n argument is optional.

For reference see the call made in `Readable:read()` at [line 307](https://github.com/luvit/luvit/blob/master/deps/stream/stream_readable.lua#L307), where `n` is overwritten by a call to `howMuchToRead`, which [at line 248 and 50](https://github.com/luvit/luvit/blob/master/deps/stream/stream_readable.lua#L248) `n` is checked for falsy values and the size of the buffer is returned,

Do note though, the stdin example given here means nothing.  The stream interface is used in many places where a read limit does make sense.

**Comment by checkraisefold** [comment]
> That is indeed correct, the n argument is optional.
> 
> For reference see the call made in `Readable:read()` at [line 307](https://github.com/luvit/luvit/blob/master/deps/stream/stream_readable.lua#L307), where `n` is overwritten by a call to `howMuchToRead`, which [at line 248 and 50](https://github.com/luvit/luvit/blob/master/deps/stream/stream_readable.lua#L248) `n` is checked for falsy values and the size of the buffer is returned,
> 
> Do note though, the stdin example given here means nothing. The stream interface is used in many places where a read limit does make sense.

I am aware that it is used in places where the read limit does make sense. I was giving one example where it being non-optional is breaking behavior.

**Comment by Bilal2453** [comment]
Thanks again for the report.  The fix is now up on the vscode addon manager.
